# CONFIGURAÇÃO DE CONEXÃO (RENDER)
spring.datasource.url=jdbc:postgresql://dpg-d6m33etactks73fqkvbg-a.oregon-postgres.render.com:5432/springboot_db_yyn7?ssl=true&sslmode=require
spring.datasource.username=springboot_db_yyn7_user
spring.datasource.password=KVZ3aB5ZqteopbzZj46qEbhk9Sn2y26M

# CONFIGURAÇÕES JPA/HIBERNATE
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# CONFIGURAÇÕES DE SEGURANÇA (JWT)
jwt.secret=MYJWTSECRET
jwt.expiration=3600000
